# ViT を直接インスタンス化するだけ
_target_: vit_pytorch.ViT
batch_size: 666

# ↓ コンストラクタ引数（好きに追加・変更可）
image_size: 224
patch_size: 16
num_classes: 2   # ← データセット側と連動
dim: 256
depth: 3
heads: 6
mlp_dim: 256
dropout: 0.2
emb_dropout: 0.2

name: vit_third

