defaults:
  - data: bean_224
  - train: base
  - model: cnn224
  - _self_
num_classes: 2
gpu: 3
hydra:
  run:
    dir: outputs/${data.name}/${model.name}/${train.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
